month-12/step-2
AleksandrDronov/algososh pull request #2
Opened 2023-01-07 12:20 UTC by AleksandrDronov

2023-01-07 13:14 UTC, ArslanDev666 commented on cypress/e2e/list.cy.js
> +      expect($el).to.have.css("border", "4px solid rgb(0, 50, 255)");
**Можно лучше:**

Здесь и далее.

Возможно лучше будет вынести стили для бордеров в константу, и потом их переиспользовать)

2023-01-07 13:28 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- все юнит-тесты проходят успешно;
- все Snapshots-тесты проходят успешны;

### **Но есть 1 замечание, которое нужно исправить:**

- Покрытие говорит, что у вас не протестировано поведение компонента `components/ui/button` при разных значениях пропса `sorting`, а также `linkedList`. Чтобы проверить покрытие тестами всех компонентов используйте команду `react-scripts test --coverage --watchAll`. https://yadi.sk/d/IaXRT88bZb67VQ.

### **Сделает код лучше:**

- В cypress лучше вынести все роуты в отдельный файлик констант, и потом их переиспользовать)

2023-01-07 13:28 UTC, ArslanDev666 commented on cypress/e2e/list.cy.js
> +      expect($el).to.have.css("border", "4px solid rgb(0, 50, 255)");
**Можно лучше:**

Здесь и далее.

Возможно лучше будет вынести стили для бордеров в константу, и потом их переиспользовать)

2023-01-08 11:36 UTC, AleksandrDronov commented
Cпасибо за комментарии. Замечания поправлены.

2023-01-08 15:14 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены;

2023-01-08 15:33 UTC, merged